package database

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"go_mangahub/manga_hub/pkg/models"
)


func SeedSampleManga(db *sql.DB) error {
	var count int
	err := db.QueryRow("SELECT COUNT(*) FROM manga").Scan(&count)
	if count > 0 {
		return err
	}

	// Sample Manga Data
mangaList := []models.Manga{
    // SHOUNEN
    {ID: "one-piece", Title: "One Piece", Author: "Eiichiro Oda", Artist: "Eiichiro Oda", Genres: []string{"Action", "Adventure", "Shounen"}, Status: "ongoing", Year: 1997, TotalChapters: 1100, TotalVolumes: 107, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A pirate's quest for the ultimate treasure.", MyAnimeList: "https://myanimelist.net/manga/13", MangaDx: "https://mangadex.org/title/a1c7c817-4e59-43b7-9365-09675a149a6f"},
    {ID: "naruto", Title: "Naruto", Author: "Masashi Kishimoto", Artist: "Masashi Kishimoto", Genres: []string{"Action", "Ninja", "Shounen"}, Status: "completed", Year: 1999, TotalChapters: 700, TotalVolumes: 72, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A young ninja who seeks recognition from his village.", MyAnimeList: "https://myanimelist.net/manga/11", MangaDx: "https://mangadex.org/title/e778a1a4-de98-4606-b8a9-8aeb1f7ef65f"},
    {ID: "bleach", Title: "Bleach", Author: "Tite Kubo", Artist: "Tite Kubo", Genres: []string{"Action", "Supernatural", "Shounen"}, Status: "completed", Year: 2001, TotalChapters: 686, TotalVolumes: 74, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A high schooler who gains the powers of a Soul Reaper.", MyAnimeList: "https://myanimelist.net/manga/12", MangaDx: "https://mangadex.org/title/baa95b05-7e65-4a25-9193-fd2c54a44b93"},
    {ID: "jujutsu-kaisen", Title: "Jujutsu Kaisen", Author: "Gege Akutami", Artist: "Gege Akutami", Genres: []string{"Action", "Supernatural", "Shounen"}, Status: "ongoing", Year: 2018, TotalChapters: 250, TotalVolumes: 26, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A boy swallows a cursed talisman and joins a secret organization of sorcerers.", MyAnimeList: "https://myanimelist.net/manga/113138", MangaDx: "https://mangadex.org/title/c52b2ce3-7f95-469c-96b0-479524fb7a1a"},
    {ID: "demon-slayer", Title: "Demon Slayer", Author: "Koyoharu Gotouge", Artist: "Koyoharu Gotouge", Genres: []string{"Action", "Demons", "Shounen"}, Status: "completed", Year: 2016, TotalChapters: 205, TotalVolumes: 23, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A boy becomes a demon slayer to save his sister and avenge his family.", MyAnimeList: "https://myanimelist.net/manga/96792", MangaDx: "https://mangadex.org/title/9f50bfe6-d0dc-4bf7-9a49-f62f28cca9a6"},
    {ID: "my-hero-academia", Title: "My Hero Academia", Author: "Kohei Horikoshi", Artist: "Kohei Horikoshi", Genres: []string{"Action", "Superpowers", "Shounen"}, Status: "completed", Year: 2014, TotalChapters: 430, TotalVolumes: 41, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A boy born without powers in a superhero society inherits the greatest ability.", MyAnimeList: "https://myanimelist.net/manga/75989", MangaDx: "https://mangadex.org/title/67a872f4-f776-4794-9df0-26db634a3e7f"},
    {ID: "attack-on-titan", Title: "Attack on Titan", Author: "Hajime Isayama", Artist: "Hajime Isayama", Genres: []string{"Action", "Drama", "Shounen"}, Status: "completed", Year: 2009, TotalChapters: 139, TotalVolumes: 34, Serialization: "Bessatsu Shounen Magazine", Publisher: "Kodansha", Description: "Humanity fights for survival against giant man-eating titans.", MyAnimeList: "https://myanimelist.net/manga/23390", MangaDx: "https://mangadex.org/title/304ceac3-8cdb-4fe9-ab28-ff30e72d8640"},
    {ID: "chainsaw-man", Title: "Chainsaw Man", Author: "Tatsuki Fujimoto", Artist: "Tatsuki Fujimoto", Genres: []string{"Action", "Horror", "Shounen"}, Status: "ongoing", Year: 2018, TotalChapters: 190, TotalVolumes: 17, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A young devil hunter merges with his devil dog to become Chainsaw Man.", MyAnimeList: "https://myanimelist.net/manga/116778", MangaDx: "https://mangadex.org/title/a77742b1-befd-49a4-bff5-1ad4e6b0ef7b"},
    {ID: "hunter-x-hunter", Title: "Hunter x Hunter", Author: "Yoshihiro Togashi", Artist: "Yoshihiro Togashi", Genres: []string{"Action", "Adventure", "Shounen"}, Status: "ongoing", Year: 1998, TotalChapters: 400, TotalVolumes: 37, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A boy sets out to find his father and become a legendary Hunter.", MyAnimeList: "https://myanimelist.net/manga/83", MangaDx: "https://mangadex.org/title/a96676be-9e5b-4433-ab83-f59f7e6f5f0b"},
    {ID: "dragon-ball", Title: "Dragon Ball", Author: "Akira Toriyama", Artist: "Akira Toriyama", Genres: []string{"Action", "Martial Arts", "Shounen"}, Status: "completed", Year: 1984, TotalChapters: 519, TotalVolumes: 42, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "Goku's adventures searching for the seven magical Dragon Balls.", MyAnimeList: "https://myanimelist.net/manga/925", MangaDx: "https://mangadex.org/title/d30b0f61-d364-4b4b-99f3-7f97de563d2d"},
    {ID: "black-clover", Title: "Black Clover", Author: "Yūki Tabata", Artist: "Yūki Tabata", Genres: []string{"Action", "Magic", "Shounen"}, Status: "ongoing", Year: 2015, TotalChapters: 370, TotalVolumes: 36, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A boy born without magic in a magic world dreams of becoming the Wizard King.", MyAnimeList: "https://myanimelist.net/manga/74352", MangaDx: "https://mangadex.org/title/f5e3abf3-b4c8-4741-8f17-f9a014290b07"},
    {ID: "spy-x-family", Title: "Spy x Family", Author: "Tatsuya Endo", Artist: "Tatsuya Endo", Genres: []string{"Comedy", "Action", "Shounen"}, Status: "ongoing", Year: 2019, TotalChapters: 100, TotalVolumes: 12, Serialization: "Shounen Jump+", Publisher: "Shueisha", Description: "A spy, an assassin, and a telepath form a fake family with real feelings.", MyAnimeList: "https://myanimelist.net/manga/119161", MangaDx: "https://mangadex.org/title/6e3553b9-ddb5-4d37-b7a3-99998044774e"},
    {ID: "haikyuu", Title: "Haikyuu!!", Author: "Haruichi Furudate", Artist: "Haruichi Furudate", Genres: []string{"Sports", "Volleyball", "Shounen"}, Status: "completed", Year: 2012, TotalChapters: 402, TotalVolumes: 45, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A short boy chases his dream of becoming a great volleyball player.", MyAnimeList: "https://myanimelist.net/manga/54541", MangaDx: "https://mangadex.org/title/d8e7083a-e31c-4e29-ad29-ce77c1dc7ce5"},
    {ID: "blue-lock", Title: "Blue Lock", Author: "Muneyuki Kaneshiro", Artist: "Yusuke Nomura", Genres: []string{"Sports", "Soccer", "Shounen"}, Status: "ongoing", Year: 2018, TotalChapters: 270, TotalVolumes: 28, Serialization: "Weekly Shounen Magazine", Publisher: "Kodansha", Description: "300 strikers compete in a radical program to create Japan's best forward.", MyAnimeList: "https://myanimelist.net/manga/119976", MangaDx: "https://mangadex.org/title/a96676be-9e5b-4433-ab83-f59f7e6f5f0b"},
    {ID: "dr-stone", Title: "Dr. Stone", Author: "Riichiro Inagaki", Artist: "Boichi", Genres: []string{"Sci-Fi", "Adventure", "Shounen"}, Status: "completed", Year: 2017, TotalChapters: 232, TotalVolumes: 26, Serialization: "Weekly Shounen Jump", Publisher: "Shueisha", Description: "A genius uses science to rebuild civilization after humanity is petrified.", MyAnimeList: "https://myanimelist.net/manga/103897", MangaDx: "https://mangadex.org/title/3e0a2c7e-7e58-4a0d-8e3f-3a7d3a77c4c9"},
    {ID: "fullmetal-alchemist", Title: "Fullmetal Alchemist", Author: "Hiromu Arakawa", Artist: "Hiromu Arakawa", Genres: []string{"Action", "Adventure", "Shounen"}, Status: "completed", Year: 2001, TotalChapters: 108, TotalVolumes: 27, Serialization: "Monthly Shounen Gangan", Publisher: "Square Enix", Description: "Two brothers use alchemy to search for the Philosopher's Stone.", MyAnimeList: "https://myanimelist.net/manga/25", MangaDx: "https://mangadex.org/title/3e0a2c7e-7e58-4a0d-8e3f-3a7d3a77c4c9"},
    {ID: "fairy-tail", Title: "Fairy Tail", Author: "Hiro Mashima", Artist: "Hiro Mashima", Genres: []string{"Action", "Magic", "Shounen"}, Status: "completed", Year: 2006, TotalChapters: 545, TotalVolumes: 63, Serialization: "Weekly Shounen Magazine", Publisher: "Kodansha", Description: "A celestial mage joins the most notorious wizard guild in the land.", MyAnimeList: "https://myanimelist.net/manga/3655", MangaDx: "https://mangadex.org/title/f0e8e87b-b544-4f1c-9c69-6e2c2f5c2568"},

    // SEINEN
    {ID: "berserk", Title: "Berserk", Author: "Kentaro Miura", Artist: "Kentaro Miura", Genres: []string{"Action", "Dark Fantasy", "Seinen"}, Status: "ongoing", Year: 1989, TotalChapters: 375, TotalVolumes: 41, Serialization: "Young Animal", Publisher: "Hakusensha", Description: "Guts, a lone mercenary, battles demons and searches for purpose in a dark world.", MyAnimeList: "https://myanimelist.net/manga/2", MangaDx: "https://mangadex.org/title/801513ba-a712-498c-8f57-cae55b38cc92"},
    {ID: "vinland-saga", Title: "Vinland Saga", Author: "Makoto Yukimura", Artist: "Makoto Yukimura", Genres: []string{"Action", "Historical", "Seinen"}, Status: "ongoing", Year: 2005, TotalChapters: 210, TotalVolumes: 27, Serialization: "Monthly Afternoon", Publisher: "Kodansha", Description: "A young Viking warrior seeks revenge and discovers the meaning of a true warrior.", MyAnimeList: "https://myanimelist.net/manga/642", MangaDx: "https://mangadex.org/title/9e07b588-7c70-4f42-8a6f-dc8a45c5a374"},
    {ID: "vagabond", Title: "Vagabond", Author: "Takehiko Inoue", Artist: "Takehiko Inoue", Genres: []string{"Action", "Historical", "Seinen"}, Status: "hiatus", Year: 1998, TotalChapters: 327, TotalVolumes: 37, Serialization: "Weekly Morning", Publisher: "Kodansha", Description: "The life of legendary swordsman Miyamoto Musashi on his path of enlightenment.", MyAnimeList: "https://myanimelist.net/manga/298", MangaDx: "https://mangadex.org/title/d5f56d2a-9dfc-4819-a1d3-c9a5d1dc9de0"},
    {ID: "monster", Title: "Monster", Author: "Naoki Urasawa", Artist: "Naoki Urasawa", Genres: []string{"Thriller", "Mystery", "Seinen"}, Status: "completed", Year: 1994, TotalChapters: 162, TotalVolumes: 18, Serialization: "Weekly Big Comic Original", Publisher: "Shogakukan", Description: "A renowned surgeon hunts the serial killer he once saved.", MyAnimeList: "https://myanimelist.net/manga/1", MangaDx: "https://mangadex.org/title/ee5605e8-e52c-4e97-9a88-90f6c59f9d52"},
    {ID: "20th-century-boys", Title: "20th Century Boys", Author: "Naoki Urasawa", Artist: "Naoki Urasawa", Genres: []string{"Mystery", "Sci-Fi", "Seinen"}, Status: "completed", Year: 1999, TotalChapters: 249, TotalVolumes: 22, Serialization: "Weekly Big Comic Spirits", Publisher: "Shogakukan", Description: "Childhood friends must stop a cult leader whose plan mirrors their own made-up story.", MyAnimeList: "https://myanimelist.net/manga/6", MangaDx: "https://mangadex.org/title/dfe49e28-6e7a-4420-8e2f-06c4f80b93ae"},
    {ID: "tokyo-ghoul", Title: "Tokyo Ghoul", Author: "Sui Ishida", Artist: "Sui Ishida", Genres: []string{"Horror", "Action", "Seinen"}, Status: "completed", Year: 2011, TotalChapters: 143, TotalVolumes: 14, Serialization: "Weekly Young Jump", Publisher: "Shueisha", Description: "A college student becomes half-ghoul and struggles between two worlds.", MyAnimeList: "https://myanimelist.net/manga/64957", MangaDx: "https://mangadex.org/title/deabc47c-8f84-4e29-8dfe-b23ee8da5edb"},
    {ID: "kingdom", Title: "Kingdom", Author: "Yasuhisa Hara", Artist: "Yasuhisa Hara", Genres: []string{"Action", "Historical", "Seinen"}, Status: "ongoing", Year: 2006, TotalChapters: 800, TotalVolumes: 69, Serialization: "Weekly Young Jump", Publisher: "Shueisha", Description: "A war orphan rises through the ranks to help unify ancient China.", MyAnimeList: "https://myanimelist.net/manga/16169", MangaDx: "https://mangadex.org/title/b4ba42a1-2877-4f6e-a254-9ece2e7b8e6a"},
    {ID: "golden-kamuy", Title: "Golden Kamuy", Author: "Satoru Noda", Artist: "Satoru Noda", Genres: []string{"Adventure", "Historical", "Seinen"}, Status: "completed", Year: 2014, TotalChapters: 314, TotalVolumes: 31, Serialization: "Weekly Young Jump", Publisher: "Shueisha", Description: "A veteran soldier and an Ainu girl hunt for hidden gold in Hokkaido.", MyAnimeList: "https://myanimelist.net/manga/79717", MangaDx: "https://mangadex.org/title/c6e66a4b-7f4f-4eba-a7b8-0c22c4d9a2e6"},
    {ID: "oshi-no-ko", Title: "Oshi no Ko", Author: "Aka Akasaka", Artist: "Mengo Yokoyari", Genres: []string{"Drama", "Mystery", "Seinen"}, Status: "completed", Year: 2020, TotalChapters: 166, TotalVolumes: 15, Serialization: "Weekly Young Jump", Publisher: "Shueisha", Description: "A doctor reincarnated as an idol's son uncovers the dark side of the entertainment industry.", MyAnimeList: "https://myanimelist.net/manga/126146", MangaDx: "https://mangadex.org/title/fe202e6a-8b0e-4c38-8f0c-7a1d6a04bc5e"},
    {ID: "kaguya-sama", Title: "Kaguya-sama: Love is War", Author: "Aka Akasaka", Artist: "Aka Akasaka", Genres: []string{"Comedy", "Romance", "Seinen"}, Status: "completed", Year: 2015, TotalChapters: 281, TotalVolumes: 28, Serialization: "Weekly Young Jump", Publisher: "Shueisha", Description: "Two geniuses try to make each other confess their love first.", MyAnimeList: "https://myanimelist.net/manga/90125", MangaDx: "https://mangadex.org/title/1f0e2013-f8a0-4e14-a07f-8e9ba5ea8af2"},
    {ID: "dorohedoro", Title: "Dorohedoro", Author: "Q Hayashida", Artist: "Q Hayashida", Genres: []string{"Action", "Fantasy", "Seinen"}, Status: "completed", Year: 2000, TotalChapters: 167, TotalVolumes: 23, Serialization: "Monthly Ikki", Publisher: "Shogakukan", Description: "A lizard-headed man searches for the sorcerer who transformed him.", MyAnimeList: "https://myanimelist.net/manga/2124", MangaDx: "https://mangadex.org/title/b00c9b3a-4c2f-4a3c-9b6a-e0e5f3d5e4c2"},
    {ID: "goodnight-punpun", Title: "Goodnight Punpun", Author: "Inio Asano", Artist: "Inio Asano", Genres: []string{"Drama", "Psychological", "Seinen"}, Status: "completed", Year: 2007, TotalChapters: 147, TotalVolumes: 13, Serialization: "Weekly Young Sunday", Publisher: "Shogakukan", Description: "The life and struggles of a boy drawn as a simple bird symbol.", MyAnimeList: "https://myanimelist.net/manga/13225", MangaDx: "https://mangadex.org/title/a8a0da3b-3e32-4e43-9347-5f37fd0ea0d2"},
    {ID: "blue-period", Title: "Blue Period", Author: "Tsubasa Yamaguchi", Artist: "Tsubasa Yamaguchi", Genres: []string{"Drama", "Art", "Seinen"}, Status: "ongoing", Year: 2017, TotalChapters: 75, TotalVolumes: 14, Serialization: "Monthly Afternoon", Publisher: "Kodansha", Description: "A popular but empty high schooler discovers a passion for painting.", MyAnimeList: "https://myanimelist.net/manga/115662", MangaDx: "https://mangadex.org/title/b3b8c8b7-f3c2-4a1e-9b6f-7e0c2b1d5a3e"},
    {ID: "grand-blue", Title: "Grand Blue Dreaming", Author: "Kenji Inoue", Artist: "Kimitake Yoshioka", Genres: []string{"Comedy", "Slice of Life", "Seinen"}, Status: "ongoing", Year: 2014, TotalChapters: 95, TotalVolumes: 19, Serialization: "Monthly Afternoon", Publisher: "Kodansha", Description: "A college student's diving club life is mostly about drinking and chaos.", MyAnimeList: "https://myanimelist.net/manga/85594", MangaDx: "https://mangadex.org/title/2de7df32-2e16-4b1e-8e6d-7c0f3a2e9b4a"},
    {ID: "parasyte", Title: "Parasyte", Author: "Hitoshi Iwaaki", Artist: "Hitoshi Iwaaki", Genres: []string{"Horror", "Sci-Fi", "Seinen"}, Status: "completed", Year: 1988, TotalChapters: 64, TotalVolumes: 8, Serialization: "Monthly Afternoon", Publisher: "Kodansha", Description: "Alien parasites invade Earth, and one bonds with a high school boy's hand.", MyAnimeList: "https://myanimelist.net/manga/339", MangaDx: "https://mangadex.org/title/c5f8b7a2-3e4d-4f1a-9c6e-8b2d1a0f5e3c"},
    {ID: "re-life", Title: "ReLife", Author: "Yayoiso", Artist: "Yayoiso", Genres: []string{"Drama", "Slice of Life", "Seinen"}, Status: "completed", Year: 2013, TotalChapters: 222, TotalVolumes: 13, Serialization: "Comico", Publisher: "TMS Entertainment", Description: "An unemployed 27-year-old is sent back to high school as a social experiment.", MyAnimeList: "https://myanimelist.net/manga/78397", MangaDx: "https://mangadex.org/title/6a1e4b3c-2d5f-4e8a-9c7b-1f0e3d2a6b4c"},

    // SHOUJO
    {ID: "nana", Title: "Nana", Author: "Ai Yazawa", Artist: "Ai Yazawa", Genres: []string{"Drama", "Music", "Shoujo"}, Status: "hiatus", Year: 2000, TotalChapters: 84, TotalVolumes: 21, Serialization: "Cookie", Publisher: "Shueisha", Description: "Two women named Nana meet by chance and become unlikely roommates in Tokyo.", MyAnimeList: "https://myanimelist.net/manga/955", MangaDx: "https://mangadex.org/title/5b2c5a7e-3d1f-4b8c-9e6a-2f0d4c1b7e5a"},
    {ID: "fruits-basket", Title: "Fruits Basket", Author: "Natsuki Takaya", Artist: "Natsuki Takaya", Genres: []string{"Romance", "Drama", "Shoujo"}, Status: "completed", Year: 1998, TotalChapters: 136, TotalVolumes: 23, Serialization: "Hana to Yume", Publisher: "Hakusensha", Description: "A girl discovers the Soma family is cursed to transform into the Chinese zodiac.", MyAnimeList: "https://myanimelist.net/manga/310", MangaDx: "https://mangadex.org/title/0e5249dd-1a88-4e3d-8cf1-52f55e4e05e4"},
    {ID: "sailor-moon", Title: "Sailor Moon", Author: "Naoko Takeuchi", Artist: "Naoko Takeuchi", Genres: []string{"Fantasy", "Magical Girl", "Shoujo"}, Status: "completed", Year: 1991, TotalChapters: 60, TotalVolumes: 18, Serialization: "Nakayoshi", Publisher: "Kodansha", Description: "A clumsy girl transforms into a guardian of justice against evil forces.", MyAnimeList: "https://myanimelist.net/manga/832", MangaDx: "https://mangadex.org/title/3b1a5c2e-4d6f-4a8b-9e7c-1f2d3b0a5e4c"},
    {ID: "cardcaptor-sakura", Title: "Cardcaptor Sakura", Author: "CLAMP", Artist: "CLAMP", Genres: []string{"Adventure", "Fantasy", "Shoujo"}, Status: "completed", Year: 1996, TotalChapters: 50, TotalVolumes: 12, Serialization: "Nakayoshi", Publisher: "Kodansha", Description: "A girl accidentally releases magical Clow Cards and must capture them all.", MyAnimeList: "https://myanimelist.net/manga/1423", MangaDx: "https://mangadex.org/title/7e3a2b1c-5d4f-4c8e-9b6a-2f1d0e3c7b5a"},
    {ID: "blue-spring-ride", Title: "Blue Spring Ride", Author: "Io Sakisaka", Artist: "Io Sakisaka", Genres: []string{"Romance", "Drama", "Shoujo"}, Status: "completed", Year: 2011, TotalChapters: 53, TotalVolumes: 13, Serialization: "Bessatsu Margaret", Publisher: "Shueisha", Description: "A girl reunites with her first love, only to find he has changed completely.", MyAnimeList: "https://myanimelist.net/manga/28025", MangaDx: "https://mangadex.org/title/4c2b1a3e-6d5f-4e9b-8c7a-1f0d2e4c6b3a"},
    {ID: "horimiya", Title: "Horimiya", Author: "HERO", Artist: "Daisuke Hagiwara", Genres: []string{"Romance", "Comedy", "Shounen"}, Status: "completed", Year: 2011, TotalChapters: 125, TotalVolumes: 16, Serialization: "Monthly GFantasy", Publisher: "Square Enix", Description: "Two students discover each other's hidden sides and fall in love.", MyAnimeList: "https://myanimelist.net/manga/44347", MangaDx: "https://mangadex.org/title/8c3d2b1a-4e5f-4c8b-9a7e-2f1d3e0c6b4a"},

    // JOSEI
    {ID: "chihayafuru", Title: "Chihayafuru", Author: "Yuki Suetsugu", Artist: "Yuki Suetsugu", Genres: []string{"Sports", "Drama", "Josei"}, Status: "completed", Year: 2007, TotalChapters: 247, TotalVolumes: 50, Serialization: "Be Love", Publisher: "Kodansha", Description: "A passionate girl pursues the top of the competitive Karuta card game world.", MyAnimeList: "https://myanimelist.net/manga/20072", MangaDx: "https://mangadex.org/title/2e3a1b4c-5d6f-4c8e-9b7a-1f0d3e2c5b4a"},
    {ID: "wotakoi", Title: "Wotakoi: Love is Hard for Otaku", Author: "Fujita", Artist: "Fujita", Genres: []string{"Comedy", "Romance", "Josei"}, Status: "completed", Year: 2014, TotalChapters: 60, TotalVolumes: 11, Serialization: "pixiv Comic", Publisher: "Ichijinsha", Description: "Two childhood friends who are otaku start dating as working adults.", MyAnimeList: "https://myanimelist.net/manga/90467", MangaDx: "https://mangadex.org/title/5b1c3a2e-4d6f-4e8b-9c7a-2f0d1e3c6b5a"},
    {ID: "honey-and-clover", Title: "Honey and Clover", Author: "Chica Umino", Artist: "Chica Umino", Genres: []string{"Drama", "Romance", "Josei"}, Status: "completed", Year: 2000, TotalChapters: 71, TotalVolumes: 10, Serialization: "CUTiE Comic", Publisher: "Shueisha", Description: "Art college students navigate love, passion, and the uncertainty of the future.", MyAnimeList: "https://myanimelist.net/manga/362", MangaDx: "https://mangadex.org/title/3c2b1a4e-5d6f-4c8b-9e7a-1f0d2e4c5b3a"},
}

	// Hardcoded One Piece for testing based on user requirement
	// onePiece := models.Manga{
	// 	ID:            "one-piece",
	// 	Title:         "One Piece (ワンピース)",
	// 	Author:        "Oda Eiichiro",
	// 	Artist:        "Oda Eiichiro",
	// 	Genres:        []string{"Action", "Adventure", "Comedy", "Drama", "Shounen"},
	// 	Status:        "Ongoing",
	// 	Year:          1997,
	// 	TotalChapters: 1100,
	// 	TotalVolumes:  107,
	// 	Serialization: "Weekly Shounen Jump",
	// 	Publisher:     "Shueisha",
	// 	Description:   "Monkey D. Luffy, a boy whose body gained the properties of rubber after eating a Devil Fruit, explores the Grand Line with his diverse crew of pirates in search of the treasure known as \"One Piece\" to become the next Pirate King.",
	// 	MyAnimeList:   "https://myanimelist.net/manga/13",
	// 	MangaDx:       "https://mangadx.org/title/a1c7c817-4e59-43b7-9365-09675a149a6f",
	// }

	// mangaList := []models.Manga{onePiece}

	// // Try to fetch more from MangaDex
	// dexManga, err := FetchMangaDex()
	// if err == nil {
	// 	mangaList = append(mangaList, dexManga...)
	// }

	// insert into database
	query := `INSERT INTO manga (id, title, author, artist, genres, status, year, total_chapters, total_volumes, serialization, publisher, description, my_anime_list, manga_dx) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

	for _, m := range mangaList {
			genreJSON, _ := json.Marshal(m.Genres)
		_, err := db.Exec(query,
			m.ID, m.Title, m.Author, m.Artist, string(genreJSON), m.Status, m.Year, m.TotalChapters, m.TotalVolumes, m.Serialization, m.Publisher, m.Description, m.MyAnimeList, m.MangaDx,
		)
		if err != nil {
			fmt.Printf("Error seeding manga %s: %s\n", m.Title, err)
		}
	}

	fmt.Println("Manga and sample progress seeded successfully!")
	return nil
}